### ISSUE TITLE
Remove `near-api-js`' `Account`object dependency from view functions

### ISSUE THREAD

**Issue by kieranroneill** [NEARBuilders/near-social-js#36]
## Summary

Currently, view functions require a dependency on the `near-api-js`' `Account` object. However, this is almost impossible to use in some contexts (like the wallet selector).

As the view function doesn't really need the whole `Account` object, we can just use the account ID.

**Comment by jaswinder6991** [comment]
I already had an issue for this https://github.com/NEARBuilders/near-social-js/issues/34 

Also this statement - "As the view function doesn't really need the whole Account object, we can just use the account ID."
It applicable for Change Methods.

**Comment by kieranroneill** [comment]
Duplicate of #34
